import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import PostForm from "../component/PostForm/PostForm";
import Post from "../component/Posts";
import Bio from "../component/Bio";
import { userAuth } from "../hooks/userAuth";


export default function Home({ posts }) {
console.log('post', posts)

  const {user, Login, logOut} = userAuth();
  console.log("user", user);
  return (
    <div className={styles.container}>
      <Head>
        <title>ConnectZee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {!user && (
      <p>
        <button onClick={Login}>Log In</button>
      </p>
    )}

{user && (
      <p>
        <button onClick={logOut}>LogOut</button>
      </p>
    )}

      <main className={styles.main}>
        <Bio
          headshots="https://pbs.twimg.com/profile_images/1406820876864077827/MCdL9Mrk_400x400.jpg"
          name="Danities Ichaba"
          tagline="Full stack javascript dev"
          role="Javascript developer"
        />

        <ul className={styles.posts}>

          {posts.map((posts) =>{
            const {post, id, date } = posts;
            return (
          <li key={id}>
            <Post
              post= {post}
              date= { date}
            />
          </li>
            )
          })}

        </ul>

{/* Allowing user to login */}
        { user && (<PostForm />)}
      </main>
    </div>
  );
}


export async function getStaticProps() {
  const response = await fetch('https://api.airtable.com/v0/appIX8WfHfdPlfr4h/post?', {
    headers: {
      Authorization:`Bearer keyvNmfcrVRDbV8ob`
  }});
  const { records } = await response.json();

  const posts = records.map((records) =>{
    return {
      id: records.id,
      ...records.field

    }
  })
  return {
    props:{
      posts
    }
  }
}
//2:34