import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.scss";
import PostForm from "../component/PostForm/PostForm";
import Post from "../component/Posts";
import Bio from "../component/Bio";
import { userAuth } from "../hooks/userAuth";

export default function Home({ posts: defaultPosts }) {
  const [posts, updatePost] = useState(defaultPosts);

  useEffect(() => {
    async function run(){
    //fetching posts data from airtable
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_ENDPOINT}/api/post`);

  // converting the data to a json
  const { posts } = await response.json();
  updatePost(posts);
    }
    run();
  }, []);

  const { user, Login, logOut } = userAuth();

  async function hanleOnSubmit(data, e){
    e.preventDefault();
    console.log('data', data);

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>ConnectZee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!user && (
        <p>
          <button onClick={Login}>Log In</button>
        </p>
      )}

      {user && (
        <p>
          <button onClick={logOut}>LogOut</button>
        </p>
      )}

      <main className={styles.main}>
        <Bio
          headshots="https://pbs.twimg.com/profile_images/1406820876864077827/MCdL9Mrk_400x400.jpg"
          name="Danities Ichaba"
          tagline="Full stack javascript dev"
          role="Javascript developer"
        />

        <ul className={styles.posts}>
          {posts.map((posts) => {
            const { post, id, date } = posts;
            const dateformat = new Date(date);
            return (
              <li key={id}>
                <Post
                  post={post}
                  date={new Intl.DateTimeFormat("en-US", {
                    dateStyle: "short",
                    timeStyle: "short",
                  }).format(dateformat)}
                />
              </li>
            );
          })}
        </ul>

        {/* Allowing user to login */}
        {user && <PostForm onSubmit={hanleOnSubmit} />}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  //fetching posts data from airtable
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_ENDPOINT}/api/post`);

  // converting the data to a json
  const { posts } = await response.json();
  return {
    props: {
      posts,
    },
  };
}
//2:48
