import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

import Post from "../component/Posts";
import Bio from "../component/Bio";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ConnectZee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Bio
          headshots="https://pbs.twimg.com/profile_images/1406820876864077827/MCdL9Mrk_400x400.jpg"
          name="Danities Ichaba"
          tagline="Full stack javascript dev"
          role="Javascript developer"
        />

        <ul className={styles.posts}>
          <li>
            <Post
              post="The biggest fight in success is the fight between what you know and what you feel"
              date="20/05/2022"
            />
          </li>

          <li>
            <Post
              post="Googling should be read and write of every developer"
              date="20/05/2022"
            />
          </li>
          <li>
            <Post post="I love it when it is Javascript" date="20/05/2022" />
          </li>
        </ul>

        <from>
          <textarea className={styles.formContent}></textarea>
          <button className={styles.formButton}>Add your thoughts</button>
        </from>
      </main>
    </div>
  );
}
